### ISSUE TITLE
求解答啊

### ISSUE THREAD

**Issue by qq664956261** [MuMuJun97/semantic_slam_mapping#2]
usr/local/include/g2o/types/slam3d/edge_se3.h: In member function ‘virtual bool g2o::EdgeSE3::setMeasurementData(const double*)’:
/usr/local/include/g2o/types/slam3d/edge_se3.h:34:24: error: ‘fromVectorQT’ is not a member of ‘g2o::internal’
         setMeasurement(internal::fromVectorQT(v));
                        ^
/usr/local/include/g2o/types/slam3d/edge_se3.h: In member function ‘virtual bool g2o::EdgeSE3::getMeasurementData(double*) const’:
/usr/local/include/g2o/types/slam3d/edge_se3.h:40:34: error: ‘_measurement’ was not declared in this scope
         v = internal::toVectorQT(_measurement);
                                  ^
src/CMakeFiles/rgbd_tutor_lib.dir/build.make:62: recipe for target 'src/CMakeFiles/rgbd_tutor_lib.dir/rgbdframe.cpp.o' failed
make[2]: *** [src/CMakeFiles/rgbd_tutor_lib.dir/rgbdframe.cpp.o] Error 1
CMakeFiles/Makefile2:124: recipe for target 'src/CMakeFiles/rgbd_tutor_lib.dir/all' failed
make[1]: *** [src/CMakeFiles/rgbd_tutor_lib.dir/all] Error 2
Makefile:83: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by qq664956261** [comment]
是不是和G2O的版本有关啊

**Comment by qq664956261** [comment]
@MuMuJun97

**Comment by qq664956261** [comment]
能给个联系方式吗

**Comment by qq664956261** [comment]
兄弟你的g20和eigen是什么版本的能给我发一份吗

**Comment by MuMuJun97** [comment]
sorry，回复不太及时，你可以参考高博的rgbd-slam的代码的依赖来编译，先尝试下这里的rgbd-slam，能运行后再加入语义的代码：https://github.com/gaoxiang12/rgbd-slam-tutor2

**Comment by MuMuJun97** [comment]
> 兄弟你的g20和eigen是什么版本的能给我发一份吗

实际上这个语义建图的代码比较旧了，之后如果有时间我会更新新的代码，而且这里的语义地图比较简单，就是粗略的把语义标签的点投到三维栅格中

**Comment by qq664956261** [comment]
那个问题已经解决了，就是用的高博的那个，现在卡在这里了，/usr/bin/ld: cannot find -lvtkproj4,要手动装vtk4吗？

**Comment by qq664956261** [comment]
坐等大神更新代码啊我也学习一下@MuMuJun97

**Comment by MuMuJun97** [comment]
> 那个问题已经解决了，就是用的高博的那个，现在卡在这里了，/usr/bin/ld: cannot find -lvtkproj4,要手动装vtk4吗？

https://haoyu.love/blog371.html 在Google上看到一些解答，不知道是否对你的问题有用，vtk这个大概是PCL里的某个依赖？我没遇到过这个问题，不过想来你是少安装了或者调整下cmake应该能避开这个问题。

**Comment by MuMuJun97** [comment]
> > 那个问题已经解决了，就是用的高博的那个，现在卡在这里了，/usr/bin/ld: cannot find -lvtkproj4,要手动装vtk4吗？
> 
> https://haoyu.love/blog371.html 在Google上看到一些解答，不知道是否对你的问题有用，vtk这个大概是PCL里的某个依赖？我没遇到过这个问题，不过想来你是少安装了或者调整下cmake应该能避开这个问题。

https://blog.csdn.net/danmeng8068/article/details/77341532

**Comment by MuMuJun97** [comment]
> 那个问题已经解决了，就是用的高博的那个，现在卡在这里了，/usr/bin/ld: cannot find -lvtkproj4,要手动装vtk4吗？

https://github.com/PointCloudLibrary/pcl/issues/1594#issuecomment-283873617
